// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsdgiqnrtrzwilpmtbeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzZGdpcW5ydHJ6d2lscG10YmVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1Mjc3MDMsImV4cCI6MjA2MTEwMzcwM30.wW9CvM1tWjTG0UEcjMdwZhpTmhfaoujZcoZd0dXFgIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);