// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prlciuqksubgwhdulwqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBybGNpdXFrc3ViZ3doZHVsd3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1OTkzMjAsImV4cCI6MjA3NjE3NTMyMH0.CoAIO0ngyG9o7VhGp5K-HVXkZc-0QUBuLtGqvo-CRpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);